name: build
on:
  push:
    paths-ignore:
      - 'docs/**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/loom-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Validate the gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build
        run: ./gradlew build